[package]
name = "osiris"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
caracat = "1.2.0"
chrono = "0.4.39"
clap = { version = "4.5.20", features = ["derive"] }
clap-verbosity-flag = "3.0.0"
csv = "1.3.1"
env_logger = "0.11.5"
log = "0.4.22"
pcap = "2.2.0"
rdkafka = { version = "0.37.0" }
tokio = { version = "1.42.0", features = ["full"] }
