services:
  redpanda:
    image: vectorized/redpanda:latest
    command: redpanda start --check=false --overprovisioned --smp 1 --memory 500M
    volumes:
      - ./config/redpanda/redpanda.yml:/etc/redpanda/redpanda.yaml:ro
    ports:
      - "9092:9092"