prober:
  id: 42

kafka:
  brokers: localhost:9092

  auth_protocol: SASL_PLAINTEXT
  auth_sasl_username: osiris
  auth_sasl_password: osiris
  auth_sasl_mechanism: SCRAM-SHA-512

  in_topics: osiris-targets
  in_group_id: osiris-targets-group

  out_topic: osiris-results
